disabled_rules: # rule identifiers to exclude from running
  - file_length
  - function_body_length
  - function_parameter_count
  - line_length
  - nesting
  - type_body_length
  - variable_name
opt_in_rules: # some rules are only opt-in
  - colon
  - comma
  - control_statement
  - empty_count
  - trailing_newline
included: # paths to include during linting. `--path` is ignored if present.
  - Source
  - Tests
excluded: # paths to ignore during linting. Takes precedence over `included`.

cyclomatic_complexity:
    ignores_case_statements: true
